### ISSUE TITLE
GUI gives "no such file" error

### ISSUE THREAD

**Issue by JeffHoogland** [poppu-mtg/StackIt#51]
Image of the decklist pasted in and the error when I press generate:

http://pix.toile-libre.org/upload/original/1493737956.png

Am I doing something wrong or is the GUI foobar?

**Comment by poppu-mtg** [comment]
hmm... is there a file called 'Aggro Scapeshift' or are you trying to name the paste board? the GUI is intended as either/or (decklist name to be found in directory, or use the paste board)

**Comment by JeffHoogland** [comment]
Maybe I'm confused on what the GUI is doing then - I need to put a file name in that top entry? I thought I put a deck name in the first line and the deck content below it.

**Comment by poppu-mtg** [comment]
ah, my bad, I have to make the GUI more explicit then. If you want to paste the deck content, then you do not need to include a deck name, otherwise the app will be looking for a decklist with the name provided.

I'll code a workaround soon, thank you for reporting this - it definitely was not on my radar.

**Comment by JeffHoogland** [comment]
Ahh yea - I just assumed it needed a deck name to put at the top.

**Comment by silasary** [comment]
Yeah, I'd assumed the same thing, when I first used it.

**Comment by poppu-mtg** [comment]
closed by #50
